export const experiences = [
  {
    role: "Freelance Web Developer",
    company: "Self-Employed",
    location: "Remote / Goa, India",
    startDate: "2025-12",
    displayDate: "Dec 2025 — Present",
    summary: "Two client websites so far: Global Tourist Centre and Techjeeva.",
    current: true,
    type: "Freelance",
    description: "Worked on two client websites while learning: Global Tourist Centre and Techjeeva.",
    achievements: [
      "Completed two paid client projects including rebuilding the Global Tourist Centre website with multilingual support.",
      "Developed the Techjeeva funding platform for FIIRE Forum (Forum for Innovation, Incubation, Research and Entrepreneurship).",
      "Implemented SEO best practices such as Schema markup, Open Graph tags, robots.txt configuration, and XML sitemap generation.",
    ],
    tags: ["Full Stack Development", "MERN Stack", "SEO Architecture", "React Frontend"],
  },
  {
    role: "Sales Intern",
    company: "Avyott",
    location: "North Goa, India",
    startDate: "2025-12",
    endDate: "2026-01",
    displayDate: "Dec 2025 — Jan 2026",
    summary: "B2B outreach for a text AI agent product. Generated two qualified leads.",
    type: "Internship",
    description: "Worked closely with product teams to understand and communicate the value proposition of a text AI agent product.",
    achievements: [
      "Conducted B2B outreach through cold calls, WhatsApp messaging, email campaigns, and LinkedIn DMs.",
      "Generated two qualified leads through consistent outreach efforts.",
      "Developed practical experience in handling client objections and understanding product-market fit.",
    ],
    tags: ["B2B Sales", "Client Communication", "Product Market Fit"],
  },
  {
    role: "Event Coordinator",
    company: "GEC Coders Club",
    location: "Goa College of Engineering",
    startDate: "2025-07",
    displayDate: "Jul 2025 — Present",
    summary: "Run coding workshops and competitions, and mentor juniors.",
    current: true,
    type: "Leadership",
    description: "Organizing and leading coding initiatives, technical workshops, and hackathon participation strategies for engineering students.",
    achievements: [
      "Organized technical workshops and coding competitions for students.",
      "Conducted sessions such as 'Getting Started with Hackathons' to help juniors enter competitive coding.",
      "Mentored junior students on technical fundamentals.",
    ],
    tags: ["Leadership", "Mentoring", "Event Management"],
  },
]
